### ISSUE TITLE
Automatic reload of regions with modified mesh-points

### ISSUE THREAD

**Issue by adtzlr** [adtzlr/felupe#583]
Follow-up of #581 

If mesh-point coordinates are changed **after** a region is created, one has to re-evaluate the region with `region.reload(mesh)` manually. Otherwise, the results are wrong.

```python
import felupe as fem

mesh = fem.Cube(n=11)
region = fem.RegionHexahedron(mesh)
field = fem.FieldsMixed(region, n=1)

boundaries, loadcase = fem.dof.uniaxial(field, axis=0, sym=False, clamped=True)
mesh.update(points=mesh.rotate(angle_deg=-90, axis=2).points)

# this is important!
region.reload(mesh)
```

See also #582

**Comment by ZAARAOUI999** [comment]
Hi @adtzlr , I'm not sure if my suggestion can solve this issue, but we can add a ```callback``` to the ```mesh.update``` method, so after updating the mesh the callback will be called internally; let's take a look:
```python
def update(self, points=None, cells=None, cell_type=None, , callback=None):
        "Update the cell and dimension attributes with a given cell array."

        if points is not None:
            self.points = points

        if cells is not None:
            self.cells = cells

        ...
        
        ############## - Added - ################
        if callable(callback):
            callback(self)
        #########################################  
```
And then, the
```python
mesh.update(points=mesh.rotate(angle_deg=-90, axis=2).points)

# this is important!
region.reload(mesh)
```
is replaced with the;
```python
mesh.update(points=mesh.rotate(angle_deg=-90, axis=2).points, callback=region.reload)
```

**Comment by adtzlr** [comment]
Hi, thanks! I was thinking about that too, i.e. to add an update-method to a region like `region.update(mesh=None, element=None, quadrature=None)`. However, this could lead to problems with the subsequent usage of template classes like `RegionHexahedron`. Currently, all FElupe classes are more or less "stand alone concepts". Your approach wouldn't change that. I'm still not sure if I should add callbacks here and there in FElupe as I think they are not very "pythonic".

**Comment by ZAARAOUI999** [comment]
Okey then, I'm sure that there's no a just one solution👌🙂, it's a matter of time, hope this fixed.

**Comment by ZAARAOUI999** [comment]
> Hi, thanks! I was thinking about that too, i.e. to add an update-method to a region like `region.update(mesh=None, element=None, quadrature=None)`. However, this could lead to problems with the subsequent usage of template classes like `RegionHexahedron`. Currently, all FElupe classes are more or less "stand alone concepts". Your approach wouldn't change that. I'm still not sure if I should add callbacks here and there in FElupe as I think they are not very "pythonic".

Okey then, I'm sure that there's no a just one solution👌🙂, it's a matter of time, hope this fixed.

**Comment by adtzlr** [comment]
If you rely on this feature, then please open a pull request. We can improve this in the future if necessary.
