### ISSUE TITLE
Formula broken in Jupyter

### ISSUE THREAD

**Issue by yvanblanchard** [adtzlr/felupe#801]
Hello,

I loaded an example of notebook in JupyterLab, and the formual are broken (see image):
![image](https://github.com/adtzlr/felupe/assets/63931618/b423e15a-6b70-4b50-97da-122fc52c13e5)

I installed Felipe with all dependencies (pip install, with 'all' option).
Could you please tell what is missing ?

Thank you!

**Comment by adtzlr** [comment]
Hi, thanks - tbh, I've never checked the notebooks! The Jupyter notebooks are automatically created by Sphinx Gallery from the Python example scripts - I'll have a look why this is happening.

**Comment by adtzlr** [comment]
It seems `pypandoc` does not ship `pandoc`. During the CI/CD run, it is not available and the rst-math blocks are not converted to Markdown.

https://pypi.org/project/pypandoc/

**Comment by adtzlr** [comment]
It seems this is only related to this example. The equations in the other examples are shown.
